[package]
  edition = "2021"
  name    = "mem_columns"
  version = "0.1.0"

[dependencies]
  anyhow     = { workspace = true }
  bumpalo    = { workspace = true }
  data_types = { path = "../data_types" }
  im         = { workspace = true }
  serde      = { workspace = true }
