[package]
  edition = "2021"
  name    = "dbexp"
  version = "0.1.0"

[workspace]
  members = [
    "hcl_queries",
    "hcl_schemas",
    "index_btree",
    "index_hash",
    "mem_columns",
    "mem_graph",
    "rest_api",
    'data_types',
  ]

  [workspace.dependencies]
    anyhow = "1.0"

    [workspace.dependencies.petgraph]
      features = ["serde-1"]
      version  = "0.6"

    [workspace.dependencies.im]
      features = ["rayon", "serde"]
      version  = "15.1"

    [workspace.dependencies.serde]
      features = ["derive"]
      version  = "1.0"

    [workspace.dependencies.bumpalo]
      features = ["boxed", "collections", "serde", "std"]
      version  = "3.16"

[dependencies]
  clap = { version = "4.5.4", features = ["derive"] }
