[package]
  edition = "2021"
  name    = "dbexp"
  version = "0.1.0"

[workspace]
  members = [
    "hcl_queries",
    "hcl_schemas",
    "index_btree",
    "index_hash",
    "mem_columns",
    "mem_graph",
    "rest_api",
    'data_types',
  ]

[dependencies]
  clap = { version = "4.5.4", features = ["derive"] }
